name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        timeout: 10
        max-score: 1
        setup-command: pip3 install -r requirements
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1

